title: Website

columns:
  - width: 1/3
    sections:
      pages:
        headline: Seiten
        type: pages
        templates:
          - home
          - treatments
          - brands
          - events
          - about
          - articles
          - shop
          - newsletter
          - terms
        sortable: true

      files:
        headline: Dateien
        type: files
        sortable: true

  - width: 2/3
    sections:
      settings:
        type: fields
        fields:
          title:
            label: Titel
            type:  text

          settingsheadline:
            label: Seiteneinstellungen
            type: headline

          name:
            label: Website-Name
            type:  text

      meta:
        type: fields
        fields:
          metaheadline:
            label: Meta Daten
            type: headline

          author:
            label: Autoren
            type:  text
            translate: false

          description:
            label: Beschreibung
            type:  textarea
            help: Kurzsbeschreibung für Suchmaschinen-Vorschau

          keywords:
            label: Schlagworte
            type:  text
            help: Schlagworte für Suchmaschinen durch Beistriche abtrennen

      contact:
        type: fields
        fields:
          contactheadline:
            label: Kontaktinformationen
            type: headline

          email:
            label: Emailadresse
            type:  text
            width: 1/2
            translate: false

          phone:
            label: Telefonnummer
            type:  text
            width: 1/2
            translate: false

          address:
            label: Adresse
            type:  textarea

          bankData:
            label: Bankdaten
            type:  textarea

      social:
        type: fields
        fields:
          socialheadline:
            label: Soziale Netzwerke
            type: headline

          facebook:
            label: Facebook URL
            type:  text
            width: 1/2
            translate: false

          instagram:
            label: Instagram URL
            type:  text
            width: 1/2
            translate: false

          twitter:
            label: Twitter URL
            type:  text
            width: 1/2
            translate: false

          linkedIn:
            label: LinkedIn URL
            type:  text
            width: 1/2
            translate: false

          socialLine:
            type: line

          newsletterHeader:
            label: Newsletter Anmeldungs-Überschrift
            type: text
            width: 1/2
            translate: false

          newsletterCall:
            label: Newsletter Anmeldungstext
            type: textarea
            width: 1/2

          newsletterIntro:
            label: Newsletter Beschreibung
            type: textarea
            width: 1/2

      shop:
        type: fields
        fields:
          shopheadline:
            label: Snipcart-Shop
            type: headline

          snipcartkey:
            label: Snip Cart API Schlüssel
            type: text

          deliveryPage:
            label: Seite zu Lieferbedingungen
            type: pages
            query: site.pages
            multiple: false
            translate: false
            width: 1/2
            help: Hier kann die Seite verknüpft werden, auf denen die Shop-Lieferbedingungen angeführt sind.

      footer:
        type: fields
        fields:
          footerheadline:
            label: Footer
            type: headline

          copyright:
            label: Copyright
            type:  text
            width: 1/3
            translate: false
            help: Copyright-Besitzer dieser Website

          design:
            label: Design
            type:  text
            width: 1/3
            translate: false
            help: Name des/der Designer/s dieser Website

          designLink:
            label: Design link
            type:  text
            width: 1/3
            translate: false
            help: Link zur Website des/der Designer/s dieser Website

          footerline:
            type: line

          footerExtensionHeadline:
            label: Überschrift des erweiterten Footers
            type: textarea
            width: 1/2
            required: true

          footerExtensionText:
            label: Text des erweiterten Footers
            type: textarea
            width: 1/2
            required: true

          footerExtensionLinkTarget:
            label: Link des erweiterten Footers - Ziel
            type: pages
            width: 1/2
            multiple: false
            required: true

          footerExtensionLinkText:
            label: Link des erweiterten Footers - Text
            type: text
            width: 1/2
            required: true

          footerExtensionImage:
            label: Hintergrund des erweiterten Footers
            type: files
            multiple: false
            required: true

      terms:
        type: fields
        fields:
          termsheadline:
            label: AGBS & Impressum
            type: headline

          termsConditionsFile:
            label: AGBS (Datei)
            type: files
            query: site.files
            multiple: false
            translate: false
            width: 1/2
            help: Hier können AGBs im Datei-Format (z.B. PDF) verknüpft werden.

          termsConditionsPage:
            label: AGBS (Seite)
            type: pages
            query: site.pages
            multiple: false
            translate: false
            width: 1/2
            help: Hier können AGBs als Seite verknüpft werden.

          legalNoticePage:
            label: Impressum (Seite)
            type: pages
            query: site.pages
            multiple: false
            translate: false
            width: 1/2
            help: Hier kann das Impressum als Seite verknüpft werden.

      cookies:
        type: fields
        fields:
          cookiesheadline:
            label: Cookie Pop-Up & Bedingungen
            type: headline

          cookieHeadline:
            label: Cookie Pop-Up Überschrift
            type: text
            width: 1/2

          cookieText:
            label: Cookie Pop-Up Text
            type: textarea

          cookieContent:
            label: Platzhalter für Cookie-exklusive Inhalte
            type: textarea
            help: Dieser Text wird an Stelle wegen Cookie-Einstellungen ausgeblendeter Inhalte angezeigt.

          cookiePolicyFile:
            label: Cookie Bedingungen (Datei)
            type: files
            query: site.files
            multiple: false
            translate: false
            width: 1/2
            help: Hier können die Cookie-Bedingungen im Datei-Format (z.B. PDF) verknüpft werden.

          cookiePolicyPage:
            label: Cookie Bedingungen (Seite)
            type: pages
            query: site.pages
            multiple: false
            translate: false
            width: 1/2
            help: Hier können die Cookie-Bedinungen als Seite verknüpft werden.
