title: Site

columns:
  - width: 1/3
    sections:
      pages:
        headline: Pages
        type: pages
        templates:
          - home
          - treatments
          - brands
          - about
          - articles
          - shop
          - newsletter
          - terms
        sortable: true

      files:
        headline: Files
        type: files
        sortable: true

  - width: 2/3
    sections:
      settings:
        type: fields
        fields:
          title:
            label: Title
            type:  text

          settingsheadline:
            label: Site settings
            type: headline

          name:
            label: Site name
            type:  text

      meta:
        type: fields
        fields:
          metaheadline:
            label: Meta data
            type: headline

          author:
            label: Authors
            type:  text
            translate: false

          description:
            label: Description
            type:  textarea
            help: This serves as a short description of your site for search engine previews.

          keywords:
            label: Keywords
            type:  text
            help: Use comma-seperated keywords to aid search engines in finding your site.

      contact:
        type: fields
        fields:
          contactheadline:
            label: Contact info
            type: headline

          email:
            label: Email address
            type:  text
            width: 1/2
            translate: false

          phone:
            label: Phone number
            type:  text
            width: 1/2
            translate: false

          address:
            label: Address
            type:  textarea

          bankData:
            label: Bank data
            type:  textarea

      social:
        type: fields
        fields:
          socialheadline:
            label: Social networks
            type: headline

          facebook:
            label: Facebook URL
            type:  text
            width: 1/2
            translate: false

          instagram:
            label: Instagram URL
            type:  text
            width: 1/2
            translate: false

          twitter:
            label: Twitter URL
            type:  text
            width: 1/2
            translate: false

          linkedIn:
            label: LinkedIn URL
            type:  text
            width: 1/2
            translate: false

          socialLine:
            type: line

          newsletterHeader:
            label: Newsletter signup headline
            type: text
            width: 1/2
            translate: false
            help: If your site features calls to action advertising your newsletter, this is where you can set the corresponding headline.

          newsletterCall:
            label: Newsletter signup text
            type: textarea
            help: If your site features calls to action advertising your newsletter, this is where you can set the corresponding text.
            width: 1/2

          newsletterIntro:
            label: Newsletter description
            type: textarea
            help: If your page uses an embedded newsletter signup form, its accompanying description can be configured here.
            width: 1/2

      shop:
        type: fields
        fields:
          shopheadline:
            label: Shop
            type: headline

          snipcartkey:
            label: Snip Cart Api Key
            type: text
            help: Copy the public Snip Cart API KEY here

          deliveryPage:
            label: Delivery information (page)
            type: pages
            query: site.pages
            multiple: false
            translate: false
            width: 1/2
            help: Link the page about delivery information here.

      footer:
        type: fields
        fields:
          footerheadline:
            label: Footer texts & links
            type: headline

          copyright:
            label: Copyright
            type:  text
            width: 1/3
            translate: false
            help: Insert the copyright holder of your website here.

          design:
            label: Design
            type:  text
            width: 1/3
            translate: false
            help: Help out your design studio by naming them here.

          designLink:
            label: Design link
            type:  text
            width: 1/3
            translate: false
            help: Help out your design studio by placing a link to their website here.

          footerline:
            type: line

          footerExtensionHeadline:
            label: Extended footer headline
            type: textarea
            width: 1/2
            required: true

          footerExtensionText:
            label: Extended footer text
            type: textarea
            width: 1/2
            required: true

          footerExtensionLinkTarget:
            label: Extended footer button target
            type: pages
            width: 1/2
            multiple: false
            required: true

          footerExtensionLinkText:
            label: Extended footer button text
            type: text
            width: 1/2
            required: true

          footerExtensionImage:
            label: Extended footer image
            type: files
            multiple: false
            required: true

      terms:
        type: fields
        fields:
          termsheadline:
            label: Terms & legal notes
            type: headline

          termsConditionsFile:
            label: Terms & conditions (file)
            type: files
            query: site.files
            multiple: false
            translate: false
            width: 1/2
            help: If your site supplies the terms & conditions as a file (f.e. in PDF format), link this file here.

          termsConditionsPage:
            label: Terms & conditions (page)
            type: pages
            query: site.pages
            multiple: false
            translate: false
            width: 1/2
            help: If your site supplies the terms & conditions in the form of a page, link that page here.

          legalNoticePage:
            label: Legal notice (page)
            type: pages
            query: site.pages
            multiple: false
            translate: false
            width: 1/2
            help: If your site features a dedicated legal notice page linked in the footer or other repeating elements, this is where you can set that link.

      cookies:
        type: fields
        fields:
          cookiesheadline:
            label: Cookie pop-up & policy
            type: headline

          cookieHeadline:
            label: Cookie pop-up headline
            type: text
            width: 1/2

          cookieText:
            label: Cookie pop-up text
            type: textarea

          cookieContent:
            label: Cookie content placeholder
            type: textarea
            help: This text is displayed instead of elements which cannot be utilized as long as the user has not given consent to the cookie policy.

          cookiePolicyFile:
            label: Cookie policy (file)
            type: files
            query: site.files
            multiple: false
            translate: false
            width: 1/2
            help: If your site supplies the terms & conditions as a file (f.e. in PDF format), link this file here.

          cookiePolicyPage:
            label: Cookie policy (page)
            type: pages
            query: site.pages
            multiple: false
            translate: false
            width: 1/2
            help: If your site supplies the cookie policy in the form of a page, link that page here.
