title: Products

columns:
  - width: 1/3
    sections:
      categories:
        headline: Categories
        type: pages
        template: products
        sortable: true
      products:
        headline: Products
        type: pages
        template: product
        sortable: true

      files:
        headline: Media
        type: files
        template: media
        sortable: true

  - width: 2/3
    sections:
      general:
        type: fields
        fields:
          title:
            label: Page title
            type: title
            translate: false

          generalSectionHeadline:
            label: General
            type: headline

          name:
            label: Page name
            type: text
            required: true

          backgroundImage:
            label: Page background
            type: files
            multiple: false
            required: true

          previewSesctionHeadline:
            label: Preview Content
            type: headline

          shortDescription:
            label: Short description
            type: textarea
            required: true
