title: Category

columns:
  - width: 1/3
    sections:
      categories:
        headline: Product Overviews
        type: pages
        template: products
        sortable: true

      files:
        headline: Media
        type: files
        template: media
        sortable: true

  - width: 2/3
    sections:
      general:
        type: fields
        fields:
          title:
            label: Page title
            type: title
            translate: false

          generalSectionHeadline:
            label: General
            type: headline

          name:
            label: Page name
            type: text
            required: true

          backgroundImage:
            label: Page background
            type: files
            multiple: false
            required: true

          previewSesctionHeadline:
            label: Preview Content
            type: headline

          shortDescription:
            label: Short description
            type: textarea
            required: true

          detailsSectionHeadline:
            label: Category Details
            type: headline

          description:
            label: Description
            type: textarea
            required: true

          headerImage:
            label: Header image
            type: files
            multiple: false
            required: true

          footerHeadline:
            label: Category Footer
            type: headline

          footerImage:
            label: Footer image
            type: files
            multiple: false
            required: true

          footerIntro:
            label: Footer Headline
            type: textarea
            required: true

          footerText:
            label: Footer Text
            type: textarea
            required: true
