title: Produkt

columns:
  - width: 1/3
    sections:
      files:
        headline: Medien
        type: files
        template: media
        sortable: true

  - width: 2/3
    sections:
      general:
        type: fields
        fields:
          title:
            label: Seitentitel
            type: title
            translate: false

          generalSectionHeadline:
            label: Allgemein
            type: headline

          brand:
            label: Marke
            type: select
            options: query
            query: 
              fetch: site.find("brands").children().filterBy("intendedTemplate", "brand")
              value: "{{ page.title }}"
              text: "{{ page.name }}"
            width: 1/3
            required: true

          name:
            label: Name
            type: text
            width: 2/3
            required: true

          price:
            label: Preis (€)
            type: text
            width: 1/2
            required: true

          size:
            label: Größe (Optional)
            type: text
            width: 1/2

          productImage:
            label: Bild
            type: files
            uploads:
              template: media
            multiple: false
            required: true

          detailsSectionHeadline:
            label: Produktdetails
            type: headline

          shortDescription:
            label: Kurzbeschreibung (Max. 100 Zeichen)
            type: textarea
            maxlength: 100
            required: true
          
          description:
            label: Beschreibung
            type: textarea
            required: true
          
          ingredients:
            label: Inhaltsstoffe (optional)
            type: textarea
            required: false

          application:
            label: Anwendung (Optional)
            type: textarea

          similarProductsSectionHeadline:
            label: Ähnliche Produkte
            type: headline

          similarProducts:
            label: Ähnliche Produkte (Optional, max. 2)
            type: pages
            query: site.find("shop").index.filterBy("intendedTemplate", "product")
            max: 2
