title: Product

columns:
  - width: 1/3
    sections:
      files:
        headline: Media
        type: files
        template: media
        sortable: true

  - width: 2/3
    sections:
      general:
        type: fields
        fields:
          title:
            label: Page title
            type: title
            translate: false

          generalSectionHeadline:
            label: General
            type: headline

          brand:
            label: Brand
            type: select
            options: query
            query: 
              fetch: site.find("brands").children().filterBy("intendedTemplate", "brand")
              value: "{{ page.title }}"
              text: "{{ page.name }}"
            width: 1/3
            required: true

          name:
            label: Name
            type: text
            width: 2/3
            required: true

          price:
            label: Price (€)
            type: text
            width: 1/2
            required: true

          size:
            label: Size (Optional)
            type: text
            width: 1/2

          productImage:
            label: Image
            type: files
            uploads:
              template: media
            multiple: false
            required: true

          detailsSectionHeadline:
            label: Product Details
            type: headline

          shortDescription:
            label: Short description (Max. 100 characters)
            type: textarea
            maxlength: 100
            required: true
          
          description:
            label: Description
            type: textarea
            required: true
          
          ingredients:
            label: Ingredients (optional)
            type: textarea
            required: false

          application:
            label: Application
            type: textarea
            required: true

          similarProductsSectionHeadline:
            label: Similar products
            type: headline

          similarProducts:
            label: Similar products (Optional, max. 2)
            type: pages
            query: site.find("shop").index.filterBy("intendedTemplate", "product")
            max: 2
