
title: Produktkategorie

columns:
  - width: 1/3
    sections:
      categories:
        headline: Produktübersichten
        type: pages
        template: products
        sortable: true

      files:
        headline: Medien
        type: files
        template: media
        sortable: true

  - width: 2/3
    sections:
      general:
        type: fields
        fields:
          title:
            label: Seitentitel
            type: title
            translate: false

          generalSectionHeadline:
            label: Allgemein
            type: headline

          name:
            label: Seitentitel
            type: text
            required: true

          previewSesctionHeadline:
            label: Vorschau
            type: headline

          shortDescription:
            label: Kurzbeschreibung (Max. 50 Zeichen)
            type: text
            maxlength: 50
            required: true

          detailsSectionHeadline:
            label: Details
            type: headline

          description:
            label: Beschreibung
            type: textarea
            required: true

          headerImage:
            label: Titelzeilenbild
            type: files
            multiple: false
            required: true