title: Produktübersicht

columns:
  - width: 1/3
    sections:
      products:
        headline: Produkte
        type: pages
        template: product
        sortable: true

      files:
        headline: Medien
        type: files
        template: media
        sortable: true

  - width: 2/3
    sections:
      general:
        type: fields
        fields:
          title:
            label: Seitentitel
            type: title
            translate: false

          generalSectionHeadline:
            label: Allgemein
            type: headline

          name:
            label: Seitentitel
            type: text
            required: true

          previewSesctionHeadline:
            label: Vorschau
            type: headline

          shortDescription:
            label: Kurzbeschreibung
            type: textarea
            required: true
