title: Product

columns:
  - width: 1/3
    sections:
      files:
        headline: Media
        type: files
        template: media
        sortable: true

  - width: 2/3
    sections:
      general:
        type: fields
        fields:
          title:
            label: Page title
            type: title
            translate: false

          generalSectionHeadline:
            label: General
            type: headline

          name:
            label: Name
            type: text
            required: true

          price:
            label: Price (€)
            type: text
            width: 1/2
            required: true

          shortDescription:
            label: Short description
            type: textarea
            required: true

          productImage:
            label: Image
            type: files
            template: media
            width: 1/2
            multiple: false
            required: true

          detailsSectionHeadline:
            label: Product Details
            type: headline

          description:
            label: Description
            type: textarea
            required: true

          brand:
            label: Brand
            type: text
            required: true

          size:
            label: Size (optional)
            type: text
            required: false

          ingredients:
            label: Ingredients (optional)
            type: textarea
            required: false

          application:
            label: Application
            type: textarea
            required: true

          similarProducts:
            label: Similar products
            type: pages
            query: site.find("shop").index.filterBy("intendedTemplate", "product")
            min: 2
            max: 2
            required: true
